name: Daily Update

permissions:
  contents: write

on:
  schedule:
    - cron: "50 11 * * *"
  workflow_dispatch:

jobs:
  daily-fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master
        with:
          token: ${{ secrets.SECRET_PAT }}
          persist-credentials: true

      - name: Connect Wireguard
        env:
          SECRET_WG: ${{ secrets.SECRET_WG }}
        run: |
          sudo apt install wireguard
          echo "Write file"
          echo "$SECRET_WG" > proton.conf
          sudo mv proton.conf /etc/wireguard/
          echo "Finish writing file"
          sudo wg-quick up proton
          sudo wg | sed "s/\(.*\(public key\|peer\|endpoint\)\): .*/\1: \(hidden\)/g"

      - name: Dependencies
        run: pip install -r ./requirements.txt

      - name: Main
        run: |
          python3 src/main.py 180 "https://www.youtube.com/@QuonTama"
          python3 src/main.py 180 "https://www.youtube.com/@makuroon99"
          python3 src/main.py 180 "https://www.youtube.com/channel/UC5bhpsL8ZUHQ9q-HOLVc82A"
          python3 src/main.py 180 "https://www.youtube.com/@yayamugi222"

      - name: Disconnect Wireguard
        run: sudo wg-quick down proton

      - name: Commit
        run: |
          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi
          
          git config user.name "GitHub Actions Daily Update Bot"
          git config user.email "<>"
          git add data
          git commit -m "Daily update"
          git push
