name: Weekly Update

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # Weekly

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master
        with:
          persist-credentials: true

      - name: Connect Wireguard
        env:
          SECRET_WG: ${{ secrets.SECRET_WG }}
        run: |
          sudo apt install wireguard
          echo "Write file"
          echo "$SECRET_WG" > proton.conf
          sudo mv proton.conf /etc/wireguard/
          echo "Finish writing file"
          sudo wg-quick up proton
          sudo wg | sed "s/\(.*\(public key|peer|endpoint\)\): .*/\1: \(hidden\)/g"

      - name: Dependencies
        run: pip install -r ./requirements.txt

      - name: Main
        run: python3 src/main.py 180 "https://www.youtube.com/@QuonTama"

      - name: Disconnect Wireguard
        run: sudo wg-quick down proton

      - name: Commit
        run: |
          git config user.name "GitHub Actions Weekly Update Bot"
          git config user.email "<>"
          git add data
          git commit -m "Weekly update"
          git push
